/* EC switch threshold with hysteresis */
#define HIGH_THRESHOLD 260
#define LOW_THRESHOLD 220

#define POINTING_DEVICE_ROTATION_90
#define PIMORONI_TRACKBALL_SCALE 3
#define PIMORONI_TRACKBALL_INTERVAL_MS 3
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
